import { INodeProperties } from 'n8n-workflow';

export const altchaFields: INodeProperties[] = [
	{
		displayName: 'Website URL',
		name: 'websiteURL',
		type: 'string',
		required: true,
		displayOptions: { show: { taskType: ['altcha'] } },
		default: '',
		description: 'The URL of the page with Altcha',
	},
	{
		displayName: 'Website Key',
		name: 'websiteKey',
		type: 'string',
		displayOptions: { show: { taskType: ['altcha'] } },
		default: '',
		description: 'Optional Altcha website key',
	},
	{
		displayName: 'User Agent',
		name: 'userAgent',
		type: 'string',
		required: true,
		displayOptions: { show: { taskType: ['altcha'] } },
		default:
			'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36',
		description: 'User-Agent header',
	},
	{
		displayName: 'Challenge',
		name: 'challenge',
		type: 'string',
		required: true,
		displayOptions: { show: { taskType: ['altcha'] } },
		default: '',
		description: 'Altcha challenge string',
	},
	{
		displayName: 'Iterations',
		name: 'iterations',
		type: 'string',
		required: true,
		displayOptions: { show: { taskType: ['altcha'] } },
		default: '',
		description: 'Number of hashing iterations',
	},
	{
		displayName: 'Salt',
		name: 'salt',
		type: 'string',
		required: true,
		displayOptions: { show: { taskType: ['altcha'] } },
		default: '',
		description: 'Salt value for challenge',
	},
	{
		displayName: 'Signature',
		name: 'signature',
		type: 'string',
		required: true,
		displayOptions: { show: { taskType: ['altcha'] } },
		default: '',
		description: 'Signature for validation',
	},
];
