import { INodeProperties } from 'n8n-workflow';

export const amazonFields: INodeProperties[] = [
	{
		displayName: 'Website URL',
		name: 'websiteURL',
		type: 'string',
		required: true,
		displayOptions: { show: { taskType: ['amazon'] } },
		default: '',
		description: 'The URL of the Amazon page with the captcha',
	},
	{
		displayName: 'Website Key',
		name: 'websiteKey',
		type: 'string',
		displayOptions: { show: { taskType: ['amazon'] } },
		default: '',
		description: 'Captcha site key (if available)',
	},
	{
		displayName: 'User Agent',
		name: 'userAgent',
		type: 'string',
		displayOptions: { show: { taskType: ['amazon'] } },
		default: '',
		description: 'Optional User-Agent header for the request',
	},
	{
		displayName: 'Captcha Script URL',
		name: 'captchaScript',
		type: 'string',
		displayOptions: { show: { taskType: ['amazon'] } },
		default: '',
		description: 'URL of the captcha SDK script',
	},
	{
		displayName: 'Challenge Script URL',
		name: 'challengeScript',
		type: 'string',
		displayOptions: { show: { taskType: ['amazon'] } },
		default: '',
		description: 'URL of the challenge script (if applicable)',
	},
	{
		displayName: 'Context',
		name: 'context',
		type: 'string',
		displayOptions: { show: { taskType: ['amazon'] } },
		default: '',
		description: 'Optional context string for the captcha',
	},
	{
		displayName: 'IV',
		name: 'iv',
		type: 'string',
		displayOptions: { show: { taskType: ['amazon'] } },
		default: '',
		description: 'Optional initialization vector for the captcha',
	},
	{
		displayName: 'Cookie Solution',
		name: 'cookieSolution',
		type: 'boolean',
		displayOptions: { show: { taskType: ['amazon'] } },
		default: true,
		description: 'Whether to solve captcha with cookie solution',
	},
];
